spring:
  application:
    name: zuul-gateway

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    gateway-bookapi:
      path: /gateway-bookapi/**
      serviceId: book-service